image:
  file: .gitpod.Dockerfile
tasks:
  - name: esp-tool
    command: npx --yes serve esp-web-flash
    openMode: tab-before
  - name: build
    openMode: tab-after
    init: |
      pio run

ports:
  - name: esp-tool
    description: ESP Tool
    port: 3000
    onOpen: open-browser